# -*- coding: utf-8 -*-
"""pynumber2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10fnfM4PxWhg7cwIfPqi9IogHjx_8m-gU
"""

import numpy as np

a1=np.arange(100,200,5)
array=a1[0:16].reshape(8,2)

array

